name: Release
on:
  push:
    tags:
      - v*
    branches:
      - test

jobs:
  build_wheels_on_ubuntu:
    name: Build wheels on ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build
        run: |
          docker pull quay.io/pypa/manylinux1_x86_64
          docker run --rm -t -v $(pwd):/io quay.io/pypa/manylinux1_x86_64 bash -c "cd /io; bash buildwheels.sh 38 "
          mkdir dist
          cp wheelhouse/prox_tv-*-cp38-cp38-manylinux1_x86_64.whl dist
          pip install wheelhouse/prox_tv-*-cp38-cp38-manylinux1_x86_64.whl
          ls -la wheelhouse

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            wheelhouse/prox_tv-*-cp38-cp38-manylinux1_x86_64.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_aarch64_wheels_on_ubuntu:
    name: Build aarch64 wheels on ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build
        run: |
          docker pull quay.io/pypa/manylinux2014_aarch64
          docker run --rm -t -v $(pwd):/io quay.io/pypa/manylinux2014_aarch64 bash -c "cd /io; bash buildwheels.sh 38 "
          mkdir dist
          cp wheelhouse/prox_tv-*-cp38-cp38-linux_aarch64.whl dist
          ls -la wheelhouse

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            wheelhouse/prox_tv-*-cp38-cp38-linux_aarch64.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_wheels_on_macos:
    name: Build wheels on macos
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build
        run: |
          pip install wheel
          pip wheel . -w wheelhouse/
          pip install delocate
          delocate-listdeps wheelhouse/*.whl
          mkdir dist
          cp wheelhouse/prox_tv-*-cp*-cp*-macosx_*.whl dist
          pip install wheelhouse/prox_tv-*-cp38-cp38-macosx_*.whl
          ls -la wheelhouse

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            wheelhouse/prox_tv-*-cp38-cp38-macosx_*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
